//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFilms.ListFilms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Crew[] CrewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Country[] CountriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Language[] LanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Studio[] StudiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Genre[] GenresField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private System.DateTime ReleaseDateField;
        
        private int RunTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgPosterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgBackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficialSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImdbCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProjectFilms.ListFilms.Crew[] Crew {
            get {
                return this.CrewField;
            }
            set {
                if ((object.ReferenceEquals(this.CrewField, value) != true)) {
                    this.CrewField = value;
                    this.RaisePropertyChanged("Crew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProjectFilms.ListFilms.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProjectFilms.ListFilms.Country[] Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProjectFilms.ListFilms.Language[] Languages {
            get {
                return this.LanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguagesField, value) != true)) {
                    this.LanguagesField = value;
                    this.RaisePropertyChanged("Languages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProjectFilms.ListFilms.Studio[] Studios {
            get {
                return this.StudiosField;
            }
            set {
                if ((object.ReferenceEquals(this.StudiosField, value) != true)) {
                    this.StudiosField = value;
                    this.RaisePropertyChanged("Studios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProjectFilms.ListFilms.Genre[] Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int RunTime {
            get {
                return this.RunTimeField;
            }
            set {
                if ((this.RunTimeField.Equals(value) != true)) {
                    this.RunTimeField = value;
                    this.RaisePropertyChanged("RunTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ImgPoster {
            get {
                return this.ImgPosterField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgPosterField, value) != true)) {
                    this.ImgPosterField = value;
                    this.RaisePropertyChanged("ImgPoster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ImgBack {
            get {
                return this.ImgBackField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgBackField, value) != true)) {
                    this.ImgBackField = value;
                    this.RaisePropertyChanged("ImgBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TagLine {
            get {
                return this.TagLineField;
            }
            set {
                if ((object.ReferenceEquals(this.TagLineField, value) != true)) {
                    this.TagLineField = value;
                    this.RaisePropertyChanged("TagLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Synopsis {
            get {
                return this.SynopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SynopsisField, value) != true)) {
                    this.SynopsisField = value;
                    this.RaisePropertyChanged("Synopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Trailer {
            get {
                return this.TrailerField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerField, value) != true)) {
                    this.TrailerField = value;
                    this.RaisePropertyChanged("Trailer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string OfficialSite {
            get {
                return this.OfficialSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficialSiteField, value) != true)) {
                    this.OfficialSiteField = value;
                    this.RaisePropertyChanged("OfficialSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ImdbCode {
            get {
                return this.ImdbCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImdbCodeField, value) != true)) {
                    this.ImdbCodeField = value;
                    this.RaisePropertyChanged("ImdbCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Crew", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Crew : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        private System.DateTime DateBirthField;
        
        private System.DateTime DateDeathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Role RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateBirth {
            get {
                return this.DateBirthField;
            }
            set {
                if ((this.DateBirthField.Equals(value) != true)) {
                    this.DateBirthField = value;
                    this.RaisePropertyChanged("DateBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateDeath {
            get {
                return this.DateDeathField;
            }
            set {
                if ((this.DateDeathField.Equals(value) != true)) {
                    this.DateDeathField = value;
                    this.RaisePropertyChanged("DateDeath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProjectFilms.ListFilms.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ProjectFilms.ListFilms.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.Film FilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectFilms.ListFilms.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewCommentField;
        
        private int RatingField;
        
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ProjectFilms.ListFilms.Film Film {
            get {
                return this.FilmField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmField, value) != true)) {
                    this.FilmField = value;
                    this.RaisePropertyChanged("Film");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProjectFilms.ListFilms.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReviewComment {
            get {
                return this.ReviewCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewCommentField, value) != true)) {
                    this.ReviewCommentField = value;
                    this.RaisePropertyChanged("ReviewComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoCodeField, value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Studio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Genre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private bool IsAdminField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListFilms.FilmsServicesSoap")]
    public interface FilmsServicesSoap {
        
        // CODEGEN: Generating message contract since element name ListFilmsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFilms", ReplyAction="*")]
        ProjectFilms.ListFilms.ListFilmsResponse ListFilms(ProjectFilms.ListFilms.ListFilmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFilms", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmsResponse> ListFilmsAsync(ProjectFilms.ListFilms.ListFilmsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilm", ReplyAction="*")]
        ProjectFilms.ListFilms.DeleteFilmResponse DeleteFilm(ProjectFilms.ListFilms.DeleteFilmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilm", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.DeleteFilmResponse> DeleteFilmAsync(ProjectFilms.ListFilms.DeleteFilmRequest request);
        
        // CODEGEN: Generating message contract since element name ListRolesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRoles", ReplyAction="*")]
        ProjectFilms.ListFilms.ListRolesResponse ListRoles(ProjectFilms.ListFilms.ListRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListRolesResponse> ListRolesAsync(ProjectFilms.ListFilms.ListRolesRequest request);
        
        // CODEGEN: Generating message contract since element name ListFilmCrewResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFilmCrew", ReplyAction="*")]
        ProjectFilms.ListFilms.ListFilmCrewResponse ListFilmCrew(ProjectFilms.ListFilms.ListFilmCrewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListFilmCrew", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmCrewResponse> ListFilmCrewAsync(ProjectFilms.ListFilms.ListFilmCrewRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFilms", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListFilmsRequestBody Body;
        
        public ListFilmsRequest() {
        }
        
        public ListFilmsRequest(ProjectFilms.ListFilms.ListFilmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListFilmsRequestBody {
        
        public ListFilmsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFilmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListFilmsResponseBody Body;
        
        public ListFilmsResponse() {
        }
        
        public ListFilmsResponse(ProjectFilms.ListFilms.ListFilmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListFilmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectFilms.ListFilms.Film[] ListFilmsResult;
        
        public ListFilmsResponseBody() {
        }
        
        public ListFilmsResponseBody(ProjectFilms.ListFilms.Film[] ListFilmsResult) {
            this.ListFilmsResult = ListFilmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilm", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.DeleteFilmRequestBody Body;
        
        public DeleteFilmRequest() {
        }
        
        public DeleteFilmRequest(ProjectFilms.ListFilms.DeleteFilmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteFilmRequestBody() {
        }
        
        public DeleteFilmRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilmResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.DeleteFilmResponseBody Body;
        
        public DeleteFilmResponse() {
        }
        
        public DeleteFilmResponse(ProjectFilms.ListFilms.DeleteFilmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteFilmResponseBody {
        
        public DeleteFilmResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRoles", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListRolesRequestBody Body;
        
        public ListRolesRequest() {
        }
        
        public ListRolesRequest(ProjectFilms.ListFilms.ListRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRolesRequestBody {
        
        public ListRolesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListRolesResponseBody Body;
        
        public ListRolesResponse() {
        }
        
        public ListRolesResponse(ProjectFilms.ListFilms.ListRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectFilms.ListFilms.Role[] ListRolesResult;
        
        public ListRolesResponseBody() {
        }
        
        public ListRolesResponseBody(ProjectFilms.ListFilms.Role[] ListRolesResult) {
            this.ListRolesResult = ListRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilmCrewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFilmCrew", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListFilmCrewRequestBody Body;
        
        public ListFilmCrewRequest() {
        }
        
        public ListFilmCrewRequest(ProjectFilms.ListFilms.ListFilmCrewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListFilmCrewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int filmId;
        
        public ListFilmCrewRequestBody() {
        }
        
        public ListFilmCrewRequestBody(int filmId) {
            this.filmId = filmId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListFilmCrewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListFilmCrewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectFilms.ListFilms.ListFilmCrewResponseBody Body;
        
        public ListFilmCrewResponse() {
        }
        
        public ListFilmCrewResponse(ProjectFilms.ListFilms.ListFilmCrewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListFilmCrewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectFilms.ListFilms.Crew[] ListFilmCrewResult;
        
        public ListFilmCrewResponseBody() {
        }
        
        public ListFilmCrewResponseBody(ProjectFilms.ListFilms.Crew[] ListFilmCrewResult) {
            this.ListFilmCrewResult = ListFilmCrewResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilmsServicesSoapChannel : ProjectFilms.ListFilms.FilmsServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilmsServicesSoapClient : System.ServiceModel.ClientBase<ProjectFilms.ListFilms.FilmsServicesSoap>, ProjectFilms.ListFilms.FilmsServicesSoap {
        
        public FilmsServicesSoapClient() {
        }
        
        public FilmsServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilmsServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmsServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmsServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectFilms.ListFilms.ListFilmsResponse ProjectFilms.ListFilms.FilmsServicesSoap.ListFilms(ProjectFilms.ListFilms.ListFilmsRequest request) {
            return base.Channel.ListFilms(request);
        }
        
        public ProjectFilms.ListFilms.Film[] ListFilms() {
            ProjectFilms.ListFilms.ListFilmsRequest inValue = new ProjectFilms.ListFilms.ListFilmsRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListFilmsRequestBody();
            ProjectFilms.ListFilms.ListFilmsResponse retVal = ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListFilms(inValue);
            return retVal.Body.ListFilmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmsResponse> ProjectFilms.ListFilms.FilmsServicesSoap.ListFilmsAsync(ProjectFilms.ListFilms.ListFilmsRequest request) {
            return base.Channel.ListFilmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmsResponse> ListFilmsAsync() {
            ProjectFilms.ListFilms.ListFilmsRequest inValue = new ProjectFilms.ListFilms.ListFilmsRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListFilmsRequestBody();
            return ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListFilmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectFilms.ListFilms.DeleteFilmResponse ProjectFilms.ListFilms.FilmsServicesSoap.DeleteFilm(ProjectFilms.ListFilms.DeleteFilmRequest request) {
            return base.Channel.DeleteFilm(request);
        }
        
        public void DeleteFilm(string id) {
            ProjectFilms.ListFilms.DeleteFilmRequest inValue = new ProjectFilms.ListFilms.DeleteFilmRequest();
            inValue.Body = new ProjectFilms.ListFilms.DeleteFilmRequestBody();
            inValue.Body.id = id;
            ProjectFilms.ListFilms.DeleteFilmResponse retVal = ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).DeleteFilm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.DeleteFilmResponse> ProjectFilms.ListFilms.FilmsServicesSoap.DeleteFilmAsync(ProjectFilms.ListFilms.DeleteFilmRequest request) {
            return base.Channel.DeleteFilmAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectFilms.ListFilms.DeleteFilmResponse> DeleteFilmAsync(string id) {
            ProjectFilms.ListFilms.DeleteFilmRequest inValue = new ProjectFilms.ListFilms.DeleteFilmRequest();
            inValue.Body = new ProjectFilms.ListFilms.DeleteFilmRequestBody();
            inValue.Body.id = id;
            return ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).DeleteFilmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectFilms.ListFilms.ListRolesResponse ProjectFilms.ListFilms.FilmsServicesSoap.ListRoles(ProjectFilms.ListFilms.ListRolesRequest request) {
            return base.Channel.ListRoles(request);
        }
        
        public ProjectFilms.ListFilms.Role[] ListRoles() {
            ProjectFilms.ListFilms.ListRolesRequest inValue = new ProjectFilms.ListFilms.ListRolesRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListRolesRequestBody();
            ProjectFilms.ListFilms.ListRolesResponse retVal = ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListRoles(inValue);
            return retVal.Body.ListRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListRolesResponse> ProjectFilms.ListFilms.FilmsServicesSoap.ListRolesAsync(ProjectFilms.ListFilms.ListRolesRequest request) {
            return base.Channel.ListRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListRolesResponse> ListRolesAsync() {
            ProjectFilms.ListFilms.ListRolesRequest inValue = new ProjectFilms.ListFilms.ListRolesRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListRolesRequestBody();
            return ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectFilms.ListFilms.ListFilmCrewResponse ProjectFilms.ListFilms.FilmsServicesSoap.ListFilmCrew(ProjectFilms.ListFilms.ListFilmCrewRequest request) {
            return base.Channel.ListFilmCrew(request);
        }
        
        public ProjectFilms.ListFilms.Crew[] ListFilmCrew(int filmId) {
            ProjectFilms.ListFilms.ListFilmCrewRequest inValue = new ProjectFilms.ListFilms.ListFilmCrewRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListFilmCrewRequestBody();
            inValue.Body.filmId = filmId;
            ProjectFilms.ListFilms.ListFilmCrewResponse retVal = ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListFilmCrew(inValue);
            return retVal.Body.ListFilmCrewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmCrewResponse> ProjectFilms.ListFilms.FilmsServicesSoap.ListFilmCrewAsync(ProjectFilms.ListFilms.ListFilmCrewRequest request) {
            return base.Channel.ListFilmCrewAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectFilms.ListFilms.ListFilmCrewResponse> ListFilmCrewAsync(int filmId) {
            ProjectFilms.ListFilms.ListFilmCrewRequest inValue = new ProjectFilms.ListFilms.ListFilmCrewRequest();
            inValue.Body = new ProjectFilms.ListFilms.ListFilmCrewRequestBody();
            inValue.Body.filmId = filmId;
            return ((ProjectFilms.ListFilms.FilmsServicesSoap)(this)).ListFilmCrewAsync(inValue);
        }
    }
}
